### PR TITLE
Add LGTM.com code quality badges

### PR DESCRIPTION
**Pull request by xcorail**
Hey there

I thought you might be interested in adding these [LGTM code quality badges](https://lgtm.com/projects/g/axiomatic-systems/Bento4/ci/) to your project. They indicate how you care about code quality and encourage your future contributors to do the same.
To get an idea of the analyses reflected by these grades, check [the alerts discovered by LGTM](https://lgtm.com/projects/g/axiomatic-systems/Bento4/alerts/?mode=tree).

N.B.: I am on the team behind LGTM.com, I'd appreciate your feedback on this initiative, whether you're interested or not, if you find time to drop me a line. Thanks.

### CODE REVIEW

**Comment by barbibulle** [comment]
Hi Xavier,

thanks for doing this. LGTM looks like a great tool. I'll spend some time over the next few days trying to eliminate as many errors/warnings as possible.

**Comment by barbibulle** [comment]
Following up on this. I've fixed most of the warnings. There is, however, an error report that seems like a false positive: https://lgtm.com/projects/g/axiomatic-systems/Bento4/snapshot/91ed5dd9ab67af43bb5094d1380254c1ca0bf9a7/files/Source/C++/Core/Ap4OddaAtom.cpp?sort=name&dir=ASC&mode=heatmap&showExcluded=false#xf9b58b3f01bacc30:1
The LGTM warning says that the resource acquired by `m_EncryptedPayload = new AP4_SubStream(stream, position, m_EncryptedDataLength);` isn't released in the class. However, the class destructor calls this: `if (m_EncryptedPayload) m_EncryptedPayload->Release();` which decrements the ref count on the object (the ref count is 1 when `new AP4_SubStream()` is called. Maybe LGTM has trouble following the call sequence, and isn't able to see that this ref-counted model does release resources correctly? @xcorail what do you think?

**Comment by barbibulle** [comment]
Also, a second issue I'm seeing with the LGTM report is that it complains that a line in `mp4-dash-encode.py` is unreachable: https://lgtm.com/projects/g/axiomatic-systems/Bento4/snapshot/15a8e778ab7e63250d538cc2d7d6579115634c36/files/Source/Python/utils/mp4-dash-encode.py#x7df7cf346d2b0c:1
But I can clearly reach that line.
For example, running the tool like this:
`python mp4-dash-encode.py -r 3 foo` (from the `Source/Python/utils` directory) will clearly reach that line and print:
`ERROR: ERROR: invalid value for --resolution argument`

**Comment by markshannon** [comment]
Yes, that's definitely a false positive. Thanks for letting us know and we should have it fixed in a week or two.
In the meantime you can suppress the alert with a comment: https://help.semmle.com/lgtm-enterprise/user/help/alert-suppression.html

**Comment by xcorail** [comment]
@barbibulle the C++ one is also a FP, I'll keep you posted on an ETA for the fix. In the meantime you can suppress the alert. 
Thanks again!

**Comment by xcorail** [comment]
@barbibulle the C++ FP should be solved with this Pull Request: https://github.com/Semmle/ql/pull/562. 
It takes a few days to update LGTM.com with a new distribution of the queries.
Thanks again for reporting the FP
Cheers

**Pull request merged**
